apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-job
spec:
  template:
    spec:
      containers:
        - name: test-job
          image: alpine:latest
          command: ["echo", "hello world"]
      restartPolicy: Never
  backoffLimit: 4
