apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-job-{{ now | date "20060102150405" }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  template:
    spec:
      containers:
        - name: test-job
          image: alpine:latest
          command: ["echo", "hello world"]
      restartPolicy: Never
  backoffLimit: 4
