apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-job
  namespace: argocd
  annotations:
    re-trigger: "{{ now }}"
spec:
  project: default
  source:
    repoURL: "git@github.com:jpa-penneo/test-job.git"
    targetRevision: main
    path: charts/
    chart: test-job
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
